default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host:     <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port:     <%= ENV.fetch("POSTGRES_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "time_register_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "time_register_test") %>

# Produção: prefira URL única (DATABASE_URL) ou mantenha como abaixo com ENVs
production:
  primary: &primary_production
    <<: *default
    # Se tiver DATABASE_URL definido, Rails já mescla automaticamente.
    database: <%= ENV.fetch("POSTGRES_PROD_DB", "time_register_production") %>
    username: <%= ENV.fetch("POSTGRES_USER", "time_register") %>
    password: <%= ENV["TIME_REGISTER_DATABASE_PASSWORD"] || ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_PROD_CACHE_DB", "time_register_production_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_PROD_QUEUE_DB", "time_register_production_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_PROD_CABLE_DB", "time_register_production_cable") %>
    migrations_paths: db/cable_migrate
